### ISSUE TITLE
Issue on page /troubleshooting/upgrade.html

### ISSUE THREAD

**Issue by haffi78** [zextras/tech-doc#732] opened 2024-10-14 11:23 UTC
Poinst to a Download which is nothing behind regards to Special Jar download.

Also UTF-8 seams to be broken after upgrade

**Comment by stefanodavid** [comment] 2024-10-14 15:29
Thanks @haffi78, we were aware of the issue, my bad. The fix should be online by this evening.

**Comment by stefanodavid** [comment] 2024-10-16 08:24
@haffi78 Yeah, that sounds very ugly. :( I forwarded your input to our PO & devs. Thank you again!

**Comment by stefanodavid** [comment] 2024-10-21 08:28
@haffi78 We have reproduced the issue by using the Icelandic characters you mentioned, so we can confirm from our side the issue for version 24.9.0. While I can not provide any official ETA, my (personal) guess is that this might be fixed in the next release (24.12.0).

**Comment by stefanodavid** [comment] 2024-10-28 16:25
@haffi we believe the problem is solved with the latest 24.9.1, can you please check? See my post on the forum https://community.zextras.com/forum/postid/9334/. If not, feel free to reopen the issue

**Closed by stefanodavid** 2024-10-28 16:25 UTC

**Comment by wxnc-haffi** [comment] 2024-10-28 16:57
@haffi78 this is for you 😄

**Comment by haffi78** [comment] 2024-10-28 17:27
Thanks !

**Comment by stefanodavid** [comment] 2024-10-30 10:00
:man_facepalming:  I guess I need some vacation... :blush:

**Comment by haffi78** [comment] 2024-10-30 13:31
Don't be to hard on yourself ! just few numbers on a forumes post! , Vactions is always good though :) , hope you get one and enjoy!
Thanks again for all the help!
